// Order of first appearance in the text (Book 1 -> Book 18)
export const PARVA_ORDER = [
    "Anukramanika Parva",
    "Paushya Parva",
    "Pauloma Parva",
    "Astika Parva",
    "Anshavatarana Parva",
    "Sambhava Parva",
    "Jatugriha Parva",
    "Hidimba Vadha Parva",
    "Baka Vadha Parva",
    "Chaitraratha Parva",
    "Svayamvara Parva",
    "Vaivahika Parva",
    "Viduragamana Rajyalabha Parva",
    "Viduragamanarajyalabha Parva",
    "Arjuna Vanavasa Parva",
    "Subhadra Harana Parva",
    "Khandavadaha Parva",
    "Sabhakriya Parva",
    "Lokapala Sabhakhyana Parva",
    "Rajasuyarambha Parva",
    "Jarasandha Vadha Parva",
    "Digvijaya Parva",
    "Arghyaharana Parva",
    "Shishupala Vadha Parva",
    "Dyuta Parva",
    "Anudyuta Parva",
    "Aranyaka Parva",
    "Kirmira Vadha Parva",
    "Arjunabhigamana Parva",
    "Kirata Parva",
    "Indralokagamana Parva",
    "Nalopakhyana Parva",
    "Tirthayatra Parva",
    "Yaksha Yuddha Parva",
    "Nivatakavacha Yuddha Parva",
    "Ajagara Parva",
    "Markandeya Samasya Parva",
    "Draupadi Satyabhama Samvada Parva",
    "Ghosha Yatra Parva",
    "Mriga Svapnodbhava Parva",
    "Vrihi Drounika Parva",
    "Draupadi Harana Parva",
    "Jayadratha Vimokshana Parva",
    "Ramopakhyana Parva",
    "Pativrata Mahatmya Parva",
    "Kundalaharana Parva",
    "Araneya Parva",
    "Pandava Pravesha Parva",
    "Kichaka Vadha Parva",
    "Goharana Parva",
    "Sainyodyoga Parva",
    "Senodyoga Parva",
    "Sanjayayana Parva",
    "Prajagara Parva",
    "Sanat Sujata Parva",
    "Yanasandhi Parva",
    "Bhagavat Yana Parva",
    "Sainya Niryana Parva",
    "Ulukadutagamana Parva",
    "Rathatiratha Sankhyana Parva",
    "Ambopakhyana Parva",
    "Jambukhanda Vinirmana Parva",
    "Bhumi Parva",
    "Bhagavadgita Parva",
    "Bhishmavadha Parva",
    "Dronabhisheka Parva",
    "Samshaptaka Vadha Parva",
    "Abhimanyu Vadha Parva",
    "Pratijna Parva",
    "Jayadratha Vadha Parva",
    "Ghatotkacha Vadha Parva",
    "Drona Vadha Parva",
    "Karna Parva",
    "Shalya Parva",
    "Gadayuddha Parva",
    "Sauptika Parva",
    "Jalapradanika Parva",
    "Rajadharmanushasana Parva",
    "Apaddharmanushasana Parva",
    "Mokshadharma Parva",
    "Mokshad Harma Parva",
    "Anushasanika Parva",
    "Ashvamedhika Parva",
    "Anugita Parva",
    "Ashramavasika Parva",
    "Putradarshana Parva",
    "Naradagamana Parva",
    "Mausala Parva",
    "Mahaprasthanika Parva",
    "Svargarohanika Parva",
];

// Which of the 18 traditional Books each sub-parva belongs to
const BOOK_BY_PARVA = {
    "Anukramanika Parva": 1,
    "Paushya Parva": 1,
    "Pauloma Parva": 1,
    "Astika Parva": 1,
    "Anshavatarana Parva": 1,
    "Sambhava Parva": 1,
    "Jatugriha Parva": 1,
    "Hidimba Vadha Parva": 1,
    "Baka Vadha Parva": 1,
    "Chaitraratha Parva": 1,
    "Svayamvara Parva": 1,
    "Vaivahika Parva": 1,
    "Viduragamana Rajyalabha Parva": 1,
    "Viduragamanarajyalabha Parva": 1,
    "Arjuna Vanavasa Parva": 1,
    "Subhadra Harana Parva": 1,
    "Khandavadaha Parva": 1,
    "Sabhakriya Parva": 2,
    "Lokapala Sabhakhyana Parva": 2,
    "Rajasuyarambha Parva": 2,
    "Jarasandha Vadha Parva": 2,
    "Digvijaya Parva": 2,
    "Arghyaharana Parva": 2,
    "Shishupala Vadha Parva": 2,
    "Dyuta Parva": 2,
    "Anudyuta Parva": 2,
    "Aranyaka Parva": 3,
    "Kirmira Vadha Parva": 3,
    "Arjunabhigamana Parva": 3,
    "Kirata Parva": 3,
    "Indralokagamana Parva": 3,
    "Nalopakhyana Parva": 3,
    "Tirthayatra Parva": 3,
    "Yaksha Yuddha Parva": 3,
    "Nivatakavacha Yuddha Parva": 3,
    "Ajagara Parva": 3,
    "Markandeya Samasya Parva": 3,
    "Draupadi Satyabhama Samvada Parva": 3,
    "Ghosha Yatra Parva": 3,
    "Mriga Svapnodbhava Parva": 3,
    "Vrihi Drounika Parva": 3,
    "Draupadi Harana Parva": 3,
    "Jayadratha Vimokshana Parva": 3,
    "Ramopakhyana Parva": 3,
    "Pativrata Mahatmya Parva": 3,
    "Kundalaharana Parva": 3,
    "Araneya Parva": 3,
    "Pandava Pravesha Parva": 4,
    "Kichaka Vadha Parva": 4,
    "Goharana Parva": 4,
    "Sainyodyoga Parva": 5,
    "Senodyoga Parva": 5,
    "Sanjayayana Parva": 5,
    "Prajagara Parva": 5,
    "Sanat Sujata Parva": 5,
    "Yanasandhi Parva": 5,
    "Bhagavat Yana Parva": 5,
    "Sainya Niryana Parva": 5,
    "Ulukadutagamana Parva": 5,
    "Rathatiratha Sankhyana Parva": 5,
    "Ambopakhyana Parva": 5,
    "Jambukhanda Vinirmana Parva": 6,
    "Bhumi Parva": 6,
    "Bhagavadgita Parva": 6,
    "Bhishmavadha Parva": 6,
    "Dronabhisheka Parva": 7,
    "Samshaptaka Vadha Parva": 7,
    "Abhimanyu Vadha Parva": 7,
    "Pratijna Parva": 7,
    "Jayadratha Vadha Parva": 7,
    "Ghatotkacha Vadha Parva": 7,
    "Drona Vadha Parva": 7,
    "Karna Parva": 8,
    "Shalya Parva": 9,
    "Gadayuddha Parva": 9,
    "Sauptika Parva": 10,
    "Jalapradanika Parva": 11,
    "Rajadharmanushasana Parva": 12,
    "Apaddharmanushasana Parva": 12,
    "Mokshadharma Parva": 12,
    "Mokshad Harma Parva": 12,
    "Anushasanika Parva": 13,
    "Ashvamedhika Parva": 14,
    "Anugita Parva": 14,
    "Ashramavasika Parva": 15,
    "Putradarshana Parva": 15,
    "Naradagamana Parva": 15,
    "Mausala Parva": 16,
    "Mahaprasthanika Parva": 17,
    "Svargarohanika Parva": 18,
};

const BOOK_LABEL = {
    1: "Adi Parva",
    2: "Sabha Parva",
    3: "Vana Parva",
    4: "Virata Parva",
    5: "Udyoga Parva",
    6: "Bhishma Parva",
    7: "Drona Parva",
    8: "Karna Parva",
    9: "Shalya Parva",
    10: "Sauptika Parva",
    11: "Stri Parva",
    12: "Shanti Parva",
    13: "Anushasana Parva",
    14: "Ashvamedhika Parva",
    15: "Ashramavasika Parva",
    16: "Mausala Parva",
    17: "Mahaprasthanika Parva",
    18: "Svargarohana Parva",
};

const EMOJI_CYCLE = ['📿', '🏹', '⚔️', '🔥', '🐘', '🌊', '👑', '🕉️', '🌳', '🏛️', '🎲', '🌙', '🦚', '🌾', '🕊️', '🌌', '📜', '🪷'];
const COLOR_CYCLE = ['#fbe9e7', '#e8f0fe', '#fff3e0', '#e8f5e9', '#f3e5f5', '#e0f7fa', '#fce4ec', '#f5f0e8'];

export function parseParvaTitle(title) {
    if (!title) return { parva: null, adhyayaLabel: null };
    const parts = title.split('·').map((p) => p.trim());
    if (parts.length < 2) return { parva: title, adhyayaLabel: null };
    return { parva: parts[0], adhyayaLabel: parts[1] };
}

export function groupChaptersByParva(chapters) {
    const buckets = new Map();

    for (const chapter of chapters || []) {
        const { parva, adhyayaLabel } = parseParvaTitle(chapter.title);
        const bucketName = parva && PARVA_ORDER.includes(parva) ? parva : 'Other';
        if (!buckets.has(bucketName)) buckets.set(bucketName, []);
        buckets.get(bucketName).push({ ...chapter, adhyayaLabel: adhyayaLabel || chapter.title });
    }

    const ordered = PARVA_ORDER
        .filter((name) => buckets.has(name))
        .map((name, idx) => {
            const book = BOOK_BY_PARVA[name];
            return {
                name,
                bookNumber: book,
                bookLabel: book ? `Book ${book} · ${BOOK_LABEL[book]}` : null,
                emoji: EMOJI_CYCLE[(book || idx) % EMOJI_CYCLE.length],
                color: COLOR_CYCLE[(book || idx) % COLOR_CYCLE.length],
                chapters: buckets.get(name),
            };
        });

    if (buckets.has('Other')) {
        ordered.push({ name: 'Other', bookLabel: null, emoji: '📜', color: '#f5f0e8', chapters: buckets.get('Other') });
    }

    return ordered;
}
